# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/arzad/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/173.4127.32/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/arzad/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/173.4127.32/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arzad/delivery/cpp_rush3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arzad/delivery/cpp_rush3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/arzad/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/173.4127.32/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/arzad/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/173.4127.32/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arzad/delivery/cpp_rush3/CMakeFiles /home/arzad/delivery/cpp_rush3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arzad/delivery/cpp_rush3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp_rush3

# Build rule for target.
cpp_rush3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_rush3
.PHONY : cpp_rush3

# fast build rule for target.
cpp_rush3/fast:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/build
.PHONY : cpp_rush3/fast

display/gtk/GTKDisplay.o: display/gtk/GTKDisplay.cpp.o

.PHONY : display/gtk/GTKDisplay.o

# target to build an object file
display/gtk/GTKDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/gtk/GTKDisplay.cpp.o
.PHONY : display/gtk/GTKDisplay.cpp.o

display/gtk/GTKDisplay.i: display/gtk/GTKDisplay.cpp.i

.PHONY : display/gtk/GTKDisplay.i

# target to preprocess a source file
display/gtk/GTKDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/gtk/GTKDisplay.cpp.i
.PHONY : display/gtk/GTKDisplay.cpp.i

display/gtk/GTKDisplay.s: display/gtk/GTKDisplay.cpp.s

.PHONY : display/gtk/GTKDisplay.s

# target to generate assembly for a file
display/gtk/GTKDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/gtk/GTKDisplay.cpp.s
.PHONY : display/gtk/GTKDisplay.cpp.s

display/ncurses/NcursesDisplay.o: display/ncurses/NcursesDisplay.cpp.o

.PHONY : display/ncurses/NcursesDisplay.o

# target to build an object file
display/ncurses/NcursesDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/NcursesDisplay.cpp.o
.PHONY : display/ncurses/NcursesDisplay.cpp.o

display/ncurses/NcursesDisplay.i: display/ncurses/NcursesDisplay.cpp.i

.PHONY : display/ncurses/NcursesDisplay.i

# target to preprocess a source file
display/ncurses/NcursesDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/NcursesDisplay.cpp.i
.PHONY : display/ncurses/NcursesDisplay.cpp.i

display/ncurses/NcursesDisplay.s: display/ncurses/NcursesDisplay.cpp.s

.PHONY : display/ncurses/NcursesDisplay.s

# target to generate assembly for a file
display/ncurses/NcursesDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/NcursesDisplay.cpp.s
.PHONY : display/ncurses/NcursesDisplay.cpp.s

display/ncurses/tool/NcursesTool.o: display/ncurses/tool/NcursesTool.cpp.o

.PHONY : display/ncurses/tool/NcursesTool.o

# target to build an object file
display/ncurses/tool/NcursesTool.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/tool/NcursesTool.cpp.o
.PHONY : display/ncurses/tool/NcursesTool.cpp.o

display/ncurses/tool/NcursesTool.i: display/ncurses/tool/NcursesTool.cpp.i

.PHONY : display/ncurses/tool/NcursesTool.i

# target to preprocess a source file
display/ncurses/tool/NcursesTool.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/tool/NcursesTool.cpp.i
.PHONY : display/ncurses/tool/NcursesTool.cpp.i

display/ncurses/tool/NcursesTool.s: display/ncurses/tool/NcursesTool.cpp.s

.PHONY : display/ncurses/tool/NcursesTool.s

# target to generate assembly for a file
display/ncurses/tool/NcursesTool.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/display/ncurses/tool/NcursesTool.cpp.s
.PHONY : display/ncurses/tool/NcursesTool.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/main.cpp.s
.PHONY : main.cpp.s

modules/AMonitorModule.o: modules/AMonitorModule.cpp.o

.PHONY : modules/AMonitorModule.o

# target to build an object file
modules/AMonitorModule.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/AMonitorModule.cpp.o
.PHONY : modules/AMonitorModule.cpp.o

modules/AMonitorModule.i: modules/AMonitorModule.cpp.i

.PHONY : modules/AMonitorModule.i

# target to preprocess a source file
modules/AMonitorModule.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/AMonitorModule.cpp.i
.PHONY : modules/AMonitorModule.cpp.i

modules/AMonitorModule.s: modules/AMonitorModule.cpp.s

.PHONY : modules/AMonitorModule.s

# target to generate assembly for a file
modules/AMonitorModule.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/AMonitorModule.cpp.s
.PHONY : modules/AMonitorModule.cpp.s

modules/CPU/CPUModule.o: modules/CPU/CPUModule.cpp.o

.PHONY : modules/CPU/CPUModule.o

# target to build an object file
modules/CPU/CPUModule.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/CPU/CPUModule.cpp.o
.PHONY : modules/CPU/CPUModule.cpp.o

modules/CPU/CPUModule.i: modules/CPU/CPUModule.cpp.i

.PHONY : modules/CPU/CPUModule.i

# target to preprocess a source file
modules/CPU/CPUModule.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/CPU/CPUModule.cpp.i
.PHONY : modules/CPU/CPUModule.cpp.i

modules/CPU/CPUModule.s: modules/CPU/CPUModule.cpp.s

.PHONY : modules/CPU/CPUModule.s

# target to generate assembly for a file
modules/CPU/CPUModule.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/CPU/CPUModule.cpp.s
.PHONY : modules/CPU/CPUModule.cpp.s

modules/PC/PCModule.o: modules/PC/PCModule.cpp.o

.PHONY : modules/PC/PCModule.o

# target to build an object file
modules/PC/PCModule.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/PC/PCModule.cpp.o
.PHONY : modules/PC/PCModule.cpp.o

modules/PC/PCModule.i: modules/PC/PCModule.cpp.i

.PHONY : modules/PC/PCModule.i

# target to preprocess a source file
modules/PC/PCModule.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/PC/PCModule.cpp.i
.PHONY : modules/PC/PCModule.cpp.i

modules/PC/PCModule.s: modules/PC/PCModule.cpp.s

.PHONY : modules/PC/PCModule.s

# target to generate assembly for a file
modules/PC/PCModule.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/PC/PCModule.cpp.s
.PHONY : modules/PC/PCModule.cpp.s

modules/time/TimeModule.o: modules/time/TimeModule.cpp.o

.PHONY : modules/time/TimeModule.o

# target to build an object file
modules/time/TimeModule.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/time/TimeModule.cpp.o
.PHONY : modules/time/TimeModule.cpp.o

modules/time/TimeModule.i: modules/time/TimeModule.cpp.i

.PHONY : modules/time/TimeModule.i

# target to preprocess a source file
modules/time/TimeModule.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/time/TimeModule.cpp.i
.PHONY : modules/time/TimeModule.cpp.i

modules/time/TimeModule.s: modules/time/TimeModule.cpp.s

.PHONY : modules/time/TimeModule.s

# target to generate assembly for a file
modules/time/TimeModule.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/time/TimeModule.cpp.s
.PHONY : modules/time/TimeModule.cpp.s

modules/user/UserModule.o: modules/user/UserModule.cpp.o

.PHONY : modules/user/UserModule.o

# target to build an object file
modules/user/UserModule.cpp.o:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/user/UserModule.cpp.o
.PHONY : modules/user/UserModule.cpp.o

modules/user/UserModule.i: modules/user/UserModule.cpp.i

.PHONY : modules/user/UserModule.i

# target to preprocess a source file
modules/user/UserModule.cpp.i:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/user/UserModule.cpp.i
.PHONY : modules/user/UserModule.cpp.i

modules/user/UserModule.s: modules/user/UserModule.cpp.s

.PHONY : modules/user/UserModule.s

# target to generate assembly for a file
modules/user/UserModule.cpp.s:
	$(MAKE) -f CMakeFiles/cpp_rush3.dir/build.make CMakeFiles/cpp_rush3.dir/modules/user/UserModule.cpp.s
.PHONY : modules/user/UserModule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cpp_rush3"
	@echo "... display/gtk/GTKDisplay.o"
	@echo "... display/gtk/GTKDisplay.i"
	@echo "... display/gtk/GTKDisplay.s"
	@echo "... display/ncurses/NcursesDisplay.o"
	@echo "... display/ncurses/NcursesDisplay.i"
	@echo "... display/ncurses/NcursesDisplay.s"
	@echo "... display/ncurses/tool/NcursesTool.o"
	@echo "... display/ncurses/tool/NcursesTool.i"
	@echo "... display/ncurses/tool/NcursesTool.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/AMonitorModule.o"
	@echo "... modules/AMonitorModule.i"
	@echo "... modules/AMonitorModule.s"
	@echo "... modules/CPU/CPUModule.o"
	@echo "... modules/CPU/CPUModule.i"
	@echo "... modules/CPU/CPUModule.s"
	@echo "... modules/PC/PCModule.o"
	@echo "... modules/PC/PCModule.i"
	@echo "... modules/PC/PCModule.s"
	@echo "... modules/time/TimeModule.o"
	@echo "... modules/time/TimeModule.i"
	@echo "... modules/time/TimeModule.s"
	@echo "... modules/user/UserModule.o"
	@echo "... modules/user/UserModule.i"
	@echo "... modules/user/UserModule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

